// Banque de cartes Codenames (Iconify SVG)
const cardPool = [
  // Nature & Éléments
  ['Lune', 'https://api.iconify.design/noto:crescent-moon.svg'],
  ['Plage', 'https://api.iconify.design/noto:beach-with-umbrella.svg'],
  ['Jardin', 'https://api.iconify.design/noto:potted-plant.svg'],
  ['Volcan', 'https://api.iconify.design/noto:volcano.svg'],
  ['Nuage', 'https://api.iconify.design/noto:cloud.svg'],
  ['Foret', 'https://api.iconify.design/noto:evergreen-tree.svg'],
  ['Etoile', 'https://api.iconify.design/noto:glowing-star.svg'],
  ['Ocean', 'https://api.iconify.design/noto:water-wave.svg'],
  ['Foudre', 'https://api.iconify.design/noto:high-voltage.svg'],
  ['Feu', 'https://api.iconify.design/noto:fire.svg'],
  ['Montagne', 'https://api.iconify.design/noto:mountain.svg'],
  ['Soleil', 'https://api.iconify.design/noto:sun.svg'],
  ['Tornade', 'https://api.iconify.design/noto:tornado.svg'],
  ['Arc-en-ciel', 'https://api.iconify.design/noto:rainbow.svg'],
  ['Fleur', 'https://api.iconify.design/noto:cherry-blossom.svg'],
  ['Cactus', 'https://api.iconify.design/noto:cactus.svg'],
  ['Planète', 'https://api.iconify.design/noto:ringed-planet.svg'],
  ['Comète', 'https://api.iconify.design/noto:comet.svg'],
  ['Ile', 'https://api.iconify.design/noto:desert-island.svg'],
  ['Flocon', 'https://api.iconify.design/noto:snowflake.svg'],
  ['Biohazard', 'https://api.iconify.design/noto:biohazard.svg'],
  ['Goutte', 'https://api.iconify.design/noto:droplet.svg'],
  ['Sang ', 'https://api.iconify.design/noto:drop-of-blood.svg'],
  ['Lotus', 'https://api.iconify.design/noto:lotus.svg'],
  ['Corail', 'https://api.iconify.design/noto:coral.svg'],
  ['Bouquet', 'https://api.iconify.design/noto:bouquet.svg'],
  ['Nid', 'https://api.iconify.design/noto:empty-nest.svg'],
  ['Bonhomme de neige', 'https://api.iconify.design/noto:snowman.svg'],
  ['Buche', 'https://api.iconify.design/noto:wood.svg'],

  // Animaux & Fantastique
  ['Dragon', 'https://api.iconify.design/noto:dragon-face.svg'],
  ['Papillon', 'https://api.iconify.design/noto:butterfly.svg'],
  ['Robot', 'https://api.iconify.design/noto:robot.svg'],
  ['Chien', 'https://api.iconify.design/noto:dog-face.svg'],
  ['Chat', 'https://api.iconify.design/noto:cat-face.svg'],
  ['Licorne', 'https://api.iconify.design/noto:unicorn.svg'],
  ['Pieuvre', 'https://api.iconify.design/noto:octopus.svg'],
  ['Requin', 'https://api.iconify.design/noto:shark.svg'],
  ['Serpent', 'https://api.iconify.design/noto:snake.svg'],
  ['Hibou', 'https://api.iconify.design/noto:owl.svg'],
  ['Aigle', 'https://api.iconify.design/noto:eagle.svg'],
  ['Dauphin', 'https://api.iconify.design/noto:dolphin.svg'],
  ['Dinosaure', 'https://api.iconify.design/noto:t-rex.svg'],
  ['Alien', 'https://api.iconify.design/noto:alien.svg'],
  ['Fantôme', 'https://api.iconify.design/noto:ghost.svg'],
  ['Abeille', 'https://api.iconify.design/noto:honeybee.svg'],
  ['Grenouille', 'https://api.iconify.design/noto:frog.svg'],
  ['Lion', 'https://api.iconify.design/noto:lion.svg'],
  ['Tortue', 'https://api.iconify.design/noto:turtle.svg'],
  ['Cheval', 'https://api.iconify.design/noto:horse.svg'],
  ['Panda', 'https://api.iconify.design/noto:panda.svg'],
  ['Cochon', 'https://api.iconify.design/noto:pig.svg'],
  ['Ours', 'https://api.iconify.design/noto:bear.svg'],
  ['Araignée', 'https://api.iconify.design/noto:spider.svg'],
  ['Coccinelle', 'https://api.iconify.design/noto:lady-beetle.svg'],
  ['Fourmi', 'https://api.iconify.design/noto:ant.svg'],
  ['Crabe', 'https://api.iconify.design/noto:crab.svg'],
  ['Chauve-souris', 'https://api.iconify.design/noto:bat.svg'],
  ['Poulpe', 'https://api.iconify.design/noto:squid.svg'],
  ['Orang-outan', 'https://api.iconify.design/noto:orangutan.svg'],
  ['Kangourou', 'https://api.iconify.design/noto:kangaroo.svg'],
  ['Chameau', 'https://api.iconify.design/noto:camel.svg'],
  ['Hippopotame', 'https://api.iconify.design/noto:hippopotamus.svg'],
  ['Zèbre', 'https://api.iconify.design/noto:zebra.svg'],
  ['Rhinocéros', 'https://api.iconify.design/noto:rhinoceros.svg'],
  ['Castor', 'https://api.iconify.design/noto:beaver.svg'],
  ['Bison', 'https://api.iconify.design/noto:bison.svg'],
  ['Poisson globe', 'https://api.iconify.design/noto:blowfish.svg'],
  ['Sanglier', 'https://api.iconify.design/noto:boar.svg'],
  ['Chenille', 'https://api.iconify.design/noto:bug.svg'],
  ['Poulet', 'https://api.iconify.design/noto:chicken.svg'],
  ['Chèvre', 'https://api.iconify.design/noto:goat.svg'],
  ['Huitre', 'https://api.iconify.design/noto:oyster.svg'],
  ['Phénix', 'https://api.iconify.design/noto:phoenix.svg'],

  // Objet & Technologie
  ['Alambic', 'https://api.iconify.design/noto:alembic.svg'],
  ['Abacus', 'https://api.iconify.design/noto:abacus.svg'],
  ['Accordéon', 'https://api.iconify.design/noto:accordion.svg'],
  ['Pansement', 'https://api.iconify.design/noto:adhesive-bandage.svg'],
  ['Ticket', 'https://api.iconify.design/noto:admission-tickets.svg'],
  ['Boussole', 'https://api.iconify.design/noto:compass.svg'],
  ['Piano', 'https://api.iconify.design/noto:musical-keyboard.svg'],
  ['Miroir', 'https://api.iconify.design/noto:mirror.svg'],
  ['Appareil photo', 'https://api.iconify.design/noto:camera.svg'],
  ['Livre', 'https://api.iconify.design/noto:books.svg'],
  ['Clé', 'https://api.iconify.design/noto:old-key.svg'],
  ['Téléphone', 'https://api.iconify.design/noto:mobile-phone.svg'],
  ['Guitare', 'https://api.iconify.design/noto:guitar.svg'],
  ['Horloge', 'https://api.iconify.design/noto:mantelpiece-clock.svg'],
  ['Sablier', 'https://api.iconify.design/noto:hourglass-done.svg'],
  ['Ampoule', 'https://api.iconify.design/noto:light-bulb.svg'],
  ['Télévision', 'https://api.iconify.design/noto:television.svg'],
  ['Microphone', 'https://api.iconify.design/noto:microphone.svg'],
  ['Batterie', 'https://api.iconify.design/noto:battery.svg'],
  ['Cadenas', 'https://api.iconify.design/noto:locked.svg'],
  ['Ciseaux', 'https://api.iconify.design/noto:scissors.svg'],
  ['Casque', 'https://api.iconify.design/noto:headphone.svg'],
  ['Parapluie', 'https://api.iconify.design/noto:umbrella.svg'],
  ['Loupe', 'https://api.iconify.design/noto:magnifying-glass-tilted-left.svg'],
  ['Bouteille', 'https://api.iconify.design/noto:baby-bottle.svg'],
  ['Seringue', 'https://api.iconify.design/noto:syringe.svg'],
  ['Ache', 'https://api.iconify.design/noto:axe.svg'],
  ['Ancre', 'https://api.iconify.design/noto:anchor.svg'],
  ['Amphore', 'https://api.iconify.design/noto:amphora.svg'],
  ['Coeur', 'https://api.iconify.design/noto:anatomical-heart.svg'],
  ['Sac à dos', 'https://api.iconify.design/noto:backpack.svg'],
  ['Bikini', 'https://api.iconify.design/noto:bikini.svg'],
  ['Bière', 'https://api.iconify.design/noto:beer-mug.svg'],
  ['Lèvre mordue', 'https://api.iconify.design/noto:biting-lip.svg'],
  ['Cigarette', 'https://api.iconify.design/noto:cigarette.svg'],
  ['Cerceuil', 'https://api.iconify.design/noto:coffin.svg'],
  ['Boule de cristal', 'https://api.iconify.design/noto:crystal-ball.svg'],
  ['Invisible', 'https://api.iconify.design/noto:dotted-line-face.svg'],
  ['Jarre', 'https://api.iconify.design/noto:jar.svg'],
  ['-18', 'https://api.iconify.design/noto:no-one-under-eighteen.svg'],
  ['Chaussettes', 'https://api.iconify.design/noto:socks.svg'],
  ['Savon', 'https://api.iconify.design/noto:soap.svg'],
  ['Eponge', 'https://api.iconify.design/noto:sponge.svg'],
  ['Toilette', 'https://api.iconify.design/noto:toilet.svg'],
  ['Urne funéraire', 'https://api.iconify.design/noto:funeral-urn.svg'],
  ['ADN', 'https://api.iconify.design/noto:dna.svg'],
  ['Crayon', 'https://api.iconify.design/noto:crayon.svg'],
  ['Flute', 'https://api.iconify.design/noto:flute.svg'],
  ['Banjo', 'https://api.iconify.design/noto:banjo.svg'],
  ['Boomerang', 'https://api.iconify.design/noto:boomerang.svg'],
  ['Eventail', 'https://api.iconify.design/noto:folding-hand-fan.svg'],
  ['Bougie', 'https://api.iconify.design/noto:candle.svg'],
  ['Balance', 'https://api.iconify.design/noto:balance-scale.svg'],
  ['Moai', 'https://api.iconify.design/noto:moai.svg'],
  ['Sac de billet', 'https://api.iconify.design/noto:money-bag.svg'],
  ['Lotion', 'https://api.iconify.design/noto:lotion-bottle.svg'],
  ['Ballerine', 'https://api.iconify.design/noto:ballet-shoes.svg'],
  ['Panier', 'https://api.iconify.design/noto:basket.svg'],
  ['Cloche', 'https://api.iconify.design/noto:bell.svg'],
  ['Lit', 'https://api.iconify.design/noto:bed.svg'],
  ['Casquette', 'https://api.iconify.design/noto:billed-cap.svg'],
  ['Bombe', 'https://api.iconify.design/noto:bomb.svg'],
  ['Marque page', 'https://api.iconify.design/noto:bookmark.svg'],
  ['Arc et flèche', 'https://api.iconify.design/noto:bow-and-arrow.svg'],
  ['Balai', 'https://api.iconify.design/noto:broom.svg'],
  ['Slip', 'https://api.iconify.design/noto:briefs.svg'],
  ['Seau', 'https://api.iconify.design/noto:bucket.svg'],
  ['Scie', 'https://api.iconify.design/noto:carpentry-saw.svg'],
  ['Béquille', 'https://api.iconify.design/noto:crutch.svg'],
  ['Stylo plume', 'https://api.iconify.design/noto:fountain-pen.svg'],
  ['Extincteur', 'https://api.iconify.design/noto:fire-extinguisher.svg'],
  ['Projecteur', 'https://api.iconify.design/noto:film-projector.svg'],
  ['DVD', 'https://api.iconify.design/noto:dvd.svg'],
  ['Clé', 'https://api.iconify.design/noto:key.svg'],
  ['Etiquette', 'https://api.iconify.design/noto:label.svg'],
  ['Rouge à lèvres', 'https://api.iconify.design/noto:lipstick.svg'],
  ['Harpe', 'https://api.iconify.design/noto:harp.svg'],
  ['Gants', 'https://api.iconify.design/noto:gloves.svg'],
  ['Kimono', 'https://api.iconify.design/noto:kimono.svg'],
  ['Blouse de laboratoire', 'https://api.iconify.design/noto:lab-coat.svg'],
  ['Tamtam', 'https://api.iconify.design/noto:long-drum.svg'],
  ['Journal', 'https://api.iconify.design/noto:newspaper.svg'],
  ['Crayon à papier', 'https://api.iconify.design/noto:pencil.svg'],
  ['Pilule', 'https://api.iconify.design/noto:pill.svg'],
  ['Pioche', 'https://api.iconify.design/noto:pick.svg'],
  ['Ventouse', 'https://api.iconify.design/noto:plunger.svg'],
  ['Bouclier', 'https://api.iconify.design/noto:shield.svg'],
  ['Saxophone', 'https://api.iconify.design/noto:saxophone.svg'],
  ['Echarpe', 'https://api.iconify.design/noto:scarf.svg'],
  ['Bourse', 'https://api.iconify.design/noto:purse.svg'],
  ['Bague', 'https://api.iconify.design/noto:ring.svg'],
  ['Lanterne', 'https://api.iconify.design/noto:red-paper-lantern.svg'],
  ['Pelle', 'https://api.iconify.design/noto:shovel.svg'],


  // Véhicules & Bâtiments
  ['Train', 'https://api.iconify.design/noto:locomotive.svg'],
  ['Château', 'https://api.iconify.design/noto:castle.svg'],
  ['Avion', 'https://api.iconify.design/noto:airplane.svg'],
  ['Fusée', 'https://api.iconify.design/noto:rocket.svg'],
  ['Bateau', 'https://api.iconify.design/noto:sailboat.svg'],
  ['Voiture', 'https://api.iconify.design/noto:automobile.svg'],
  ['Voiture de police', 'https://api.iconify.design/noto:police-car.svg'],
  ['Vélo', 'https://api.iconify.design/noto:bicycle.svg'],
  ['Télécabine', 'https://api.iconify.design/noto:aerial-tramway.svg'],
  ['Temple', 'https://api.iconify.design/noto:classical-building.svg'],
  ['Trotinette', 'https://api.iconify.design/noto:kick-scooter.svg'],
  ['Bus', 'https://api.iconify.design/noto:bus.svg'],
  ['Tracteur', 'https://api.iconify.design/noto:tractor.svg'],
  ['Tente', 'https://api.iconify.design/noto:camping.svg'],
  ['Maison', 'https://api.iconify.design/noto:house.svg'],
  ['Maison en ruine', 'https://api.iconify.design/noto:derelict-house.svg'],
  ['Mosqué', 'https://api.iconify.design/noto:mosque.svg'],
  ['Eglise', 'https://api.iconify.design/noto:church.svg'],
  ['Synagogue', 'https://api.iconify.design/noto:synagogue.svg'],
  ['Banque', 'https://api.iconify.design/noto:bank.svg'],
  ['Hutte', 'https://api.iconify.design/noto:hut.svg'],
  ['Love Hotel', 'https://api.iconify.design/noto:love-hotel.svg'],
  ['Cirque', 'https://api.iconify.design/noto:circus-tent.svg'],
  ['Hélicoptère', 'https://api.iconify.design/noto:helicopter.svg'],
  ['Hopital', 'https://api.iconify.design/noto:hospital.svg'],
  ['Métro', 'https://api.iconify.design/noto:metro.svg'],
  ['Moto', 'https://api.iconify.design/noto:motorcycle.svg'],
  ['Taxi', 'https://api.iconify.design/noto:taxi.svg'],
  ['Formule 1', 'https://api.iconify.design/noto:racing-car.svg'],
  ['Bateau à voile', 'https://api.iconify.design/noto:sailboat.svg'],

  
  // Nourriture & Loisirs
  ['Pizza', 'https://api.iconify.design/noto:pizza.svg'],
  ['Baguette', 'https://api.iconify.design/noto:baguette-bread.svg'],
  ['Banane', 'https://api.iconify.design/noto:banana.svg'],
  ['Poivron', 'https://api.iconify.design/noto:bell-pepper.svg'],
  ['Myrtille', 'https://api.iconify.design/noto:blueberries.svg'],
  ['Bonbon', 'https://api.iconify.design/noto:candy.svg'],
  ['Bubble tea', 'https://api.iconify.design/noto:bubble-tea.svg'],
  ['Chataigne', 'https://api.iconify.design/noto:chestnut.svg'],
  ['Cerise', 'https://api.iconify.design/noto:cherries.svg'],
  ['Fromage', 'https://api.iconify.design/noto:cheese-wedge.svg'],
  ['Carotte', 'https://api.iconify.design/noto:carrot.svg'],
  ['Noix de coco', 'https://api.iconify.design/noto:coconut.svg'],
  ['Croissant', 'https://api.iconify.design/noto:croissant.svg'],
  ['Concombre', 'https://api.iconify.design/noto:cucumber.svg'],
  ['Dango', 'https://api.iconify.design/noto:dango.svg'],
  ['Flan', 'https://api.iconify.design/noto:custard.svg'],
  ['Frite', 'https://api.iconify.design/noto:french-fries.svg'],
  ['Kiwi', 'https://api.iconify.design/noto:kiwi-fruit.svg'],
  ['Citron', 'https://api.iconify.design/noto:lemon.svg'],
  ['Sucette', 'https://api.iconify.design/noto:lollipop.svg'],
  ['Mangue', 'https://api.iconify.design/noto:mango.svg'],
  ['Raisin', 'https://api.iconify.design/noto:grapes.svg'],
  ['Gingembre', 'https://api.iconify.design/noto:ginger-root.svg'],
  ['Miel', 'https://api.iconify.design/noto:honey-pot.svg'],
  ['Melon', 'https://api.iconify.design/noto:melon.svg'],
  ['Olive', 'https://api.iconify.design/noto:olive.svg'],
  ['Petits pois', 'https://api.iconify.design/noto:pea-pod.svg'],
  ['Oignon', 'https://api.iconify.design/noto:onion.svg'],
  ['Ananas', 'https://api.iconify.design/noto:pineapple.svg'],
  ['Couronne', 'https://api.iconify.design/noto:crown.svg'],
  ['Pomme', 'https://api.iconify.design/noto:red-apple.svg'],
  ['Gâteau', 'https://api.iconify.design/noto:birthday-cake.svg'],
  ['Glace', 'https://api.iconify.design/noto:soft-ice-cream.svg'],
  ['Café', 'https://api.iconify.design/noto:hot-beverage.svg'],
  ['Burger', 'https://api.iconify.design/noto:hamburger.svg'],
  ['Donut', 'https://api.iconify.design/noto:doughnut.svg'],
  ['Fraise', 'https://api.iconify.design/noto:strawberry.svg'],
  ['Avocat', 'https://api.iconify.design/noto:avocado.svg'],
  ['Trophée', 'https://api.iconify.design/noto:trophy.svg'],
  ['Manette', 'https://api.iconify.design/noto:video-game.svg'],
  ['Dés', 'https://api.iconify.design/noto:game-die.svg'],
  ['Ballon', 'https://api.iconify.design/noto:soccer-ball.svg'],
  ['Cadeau', 'https://api.iconify.design/noto:wrapped-gift.svg'],
  ['Médaille', 'https://api.iconify.design/noto:sports-medal.svg'],
  ['Masque', 'https://api.iconify.design/noto:performing-arts.svg'],
  ['Pinceau', 'https://api.iconify.design/noto:paintbrush.svg'],
  ['Diamant', 'https://api.iconify.design/noto:gem-stone.svg'],
  ['Trésor', 'https://api.iconify.design/noto:treasure-chest.svg'],
  ['Pièce', 'https://api.iconify.design/noto:coin.svg'],
  ['Steak', 'https://api.iconify.design/noto:cut-of-meat.svg'],
  ['Maïs', 'https://api.iconify.design/noto:ear-of-corn.svg'],
  ['Aubergine', 'https://api.iconify.design/noto:eggplant.svg'],
  ['Canoé', 'https://api.iconify.design/noto:canoe.svg'],
  ['Curling', 'https://api.iconify.design/noto:curling-stone.svg'],
  ['Baseball', 'https://api.iconify.design/noto:baseball.svg'],
  ['Basketball', 'https://api.iconify.design/noto:basketball.svg'],
  ['Football américain', 'https://api.iconify.design/noto:american-football.svg'],
  ['Hockey', 'https://api.iconify.design/noto:ice-hockey.svg'],
  ['Bowling', 'https://api.iconify.design/noto:bowling.svg'],
  ['Luge', 'https://api.iconify.design/noto:sled.svg'],
  ['Volleyball', 'https://api.iconify.design/noto:volleyball.svg'],
  ['Frisbee', 'https://api.iconify.design/noto:flying-disc.svg'],
  ['Machine à sous', 'https://api.iconify.design/noto:slot-machine.svg'],

  // Personnages & Métiers
  ['Geler', 'https://api.iconify.design/noto:cold-face.svg'],
  ['Clown', 'https://api.iconify.design/noto:clown-face.svg'],
  ['Déguiser', 'https://api.iconify.design/noto:disguised-face.svg'],
  ['Fée', 'https://api.iconify.design/noto:fairy.svg'],
  ['Soudeur', 'https://api.iconify.design/noto:factory-worker.svg'],
  ['Fermier', 'https://api.iconify.design/noto:farmer.svg'],
  ['Pompier', 'https://api.iconify.design/noto:firefighter.svg'],
  ['Génie', 'https://api.iconify.design/noto:genie.svg'],
  ['Garde', 'https://api.iconify.design/noto:guard.svg'],
  ['Big-foot', 'https://api.iconify.design/noto:hairy-creature.svg'],
  ['Médecin', 'https://api.iconify.design/noto:health-worker.svg'],
  ['Cavalier', 'https://api.iconify.design/noto:horse-racing.svg'],
  ['Mage', 'https://api.iconify.design/noto:mage.svg'],
  ['Peintre', 'https://api.iconify.design/noto:man-artist.svg'],
  ['Cycliste', 'https://api.iconify.design/noto:man-biking.svg'],
  ['Escalade', 'https://api.iconify.design/noto:man-climbing.svg'],
  ['Détective', 'https://api.iconify.design/noto:man-detective.svg'],
  ['Pilote', 'https://api.iconify.design/noto:man-pilot.svg'],
  ['Chanteur', 'https://api.iconify.design/noto:man-singer.svg'],
  ['Super-héros', 'https://api.iconify.design/noto:man-superhero.svg'],
  ['Super-vilain', 'https://api.iconify.design/noto:man-supervillain.svg'],
  ['Surfeur', 'https://api.iconify.design/noto:man-surfing.svg'],
  ['Sirène', 'https://api.iconify.design/noto:mermaid.svg'],
  ['Ninja', 'https://api.iconify.design/noto:ninja.svg'],
  ['Astronaute', 'https://api.iconify.design/noto:astronaut.svg'],
  ['Bébé', 'https://api.iconify.design/noto:baby-dark-skin-tone.svg'],
  ['Handicapé', 'https://api.iconify.design/noto:wheelchair-symbol.svg'],
  ['Transgenre', 'https://api.iconify.design/noto:transgender-symbol.svg'],
  ['Mère allaitante', 'https://api.iconify.design/noto:breast-feeding-medium-skin-tone.svg'],
  ['Cuisinier', 'https://api.iconify.design/noto:cook-medium-dark-skin-tone.svg'],
  ['Couple hétéro', 'https://api.iconify.design/noto:couple-with-heart-woman-man.svg'],
  ['Couple gay', 'https://api.iconify.design/noto:couple-with-heart-man-man.svg'],
  ['Couple lesbienne', 'https://api.iconify.design/noto:couple-with-heart-woman-woman.svg'],
  ['Baver', 'https://api.iconify.design/noto:drooling-face.svg'],
  ['Adulte et garçon', 'https://api.iconify.design/noto:family-adult-child.svg'],
  ['Adulte et fille', 'https://api.iconify.design/noto:family-man-girl.svg'],
  ['Femelle', 'https://api.iconify.design/noto:female-sign.svg'],
  ['Male', 'https://api.iconify.design/noto:male-sign.svg'],
  ['Pied', 'https://api.iconify.design/noto:foot-light-skin-tone.svg'],
  ['Prier', 'https://api.iconify.design/noto:folded-hands-light-skin-tone.svg'],
  ['Juge', 'https://api.iconify.design/noto:judge-medium-light-skin-tone.svg'],
  ['Croix chrétienne', 'https://api.iconify.design/noto:latin-cross.svg'],
  ['Etoile de David', 'https://api.iconify.design/noto:star-of-david.svg'],
  ['Etoile et croissant', 'https://api.iconify.design/noto:star-and-crescent.svg'],
  ['Roux', 'https://api.iconify.design/noto:man-dark-skin-tone-red-hair.svg'],
  ['Elf', 'https://api.iconify.design/noto:man-elf-light-skin-tone.svg'],
  ['Fauteuil roulant', 'https://api.iconify.design/noto:man-in-manual-wheelchair.svg'],
  ['Zombie', 'https://api.iconify.design/noto:man-zombie.svg'],
  ['Aveugle', 'https://api.iconify.design/noto:man-with-white-cane.svg'],
  ['Homme avec un turban', 'https://api.iconify.design/noto:man-wearing-turban-medium-skin-tone.svg'],
  ['Homme en marié', 'https://api.iconify.design/noto:man-with-veil.svg'],
  ['Bunny Boys', 'https://api.iconify.design/noto:men-with-bunny-ears-light-skin-tone-dark-skin-tone.svg'],
  ['Bunny Girls', 'https://api.iconify.design/noto:women-with-bunny-ears-light-skin-tone-dark-skin-tone.svg'],
  ['Control de police', 'https://api.iconify.design/noto:passport-control.svg'],
  ['Policier', 'https://api.iconify.design/noto:police-officer-medium-light-skin-tone.svg'],
  ['Homme enceinte', 'https://api.iconify.design/noto:pregnant-person.svg'],
  ['Drapeau transgenre', 'https://api.iconify.design/noto:transgender-flag.svg'],
  ['Drapeau arc-en-ciel', 'https://api.iconify.design/noto:rainbow-flag.svg'],
  ['Drapeau pirate', 'https://api.iconify.design/noto:pirate-flag.svg'],
  ['Langue', 'https://api.iconify.design/noto:tongue.svg'],
  ['Mariage', 'https://api.iconify.design/noto:wedding.svg'],
  ['Femme à barbe', 'https://api.iconify.design/noto:woman-beard.svg'],
  ['Chauve', 'https://api.iconify.design/noto:man-light-skin-tone-bald.svg'],

  //Symbole
  ['Caducée', 'https://api.iconify.design/noto:medical-symbol.svg'],
  ['Paie', 'https://api.iconify.design/noto:peace-symbol.svg'],
  ['Recyclage', 'https://api.iconify.design/noto:recycling-symbol.svg'],
  ['Wifi', 'https://api.iconify.design/noto:wireless.svg'],
  ['Tâche', 'https://api.iconify.design/noto:splatter.svg'],
  ['Yin yang', 'https://api.iconify.design/noto:yin-yang.svg'],
  ['Attention', 'https://api.iconify.design/noto:warning.svg']
];

module.exports = cardPool;
